remove constraint on main
Signed-off-by: zhichao-aws <zhichaog@amazon.com>

diff --git a/.github/workflows/model_uploader.yml b/.github/workflows/model_uploader.yml
--- a/.github/workflows/model_uploader.yml
+++ b/.github/workflows/model_uploader.yml
@@ -83,11 +83,11 @@ jobs:
   init-workflow-var:
     runs-on: 'ubuntu-latest'
     steps:
-    - name: Fail if branch is not main
-      if: github.ref != 'refs/heads/main'
-      run: |
-         echo "This workflow should only be triggered on 'main' branch"
-         exit 1
+    # - name: Fail if branch is not main
+    #   if: github.ref != 'refs/heads/main'
+    #   run: |
+    #      echo "This workflow should only be triggered on 'main' branch"
+    #      exit 1
     - name: Parse custom params from json string
       # Handles dynamic parameter configuration with three-level fallback:
       # 1. Default values initialized at script start
